version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URL: mongodb+srv://Shogher:1234@cluster0.sqn8msf.mongodb.net/
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
